export const TaskCategories = [
	"All",
	"Academic Assistance",
	"Tutor Home/Virtual",
	"Books Rent/Buy",
	"Vehicle Rent",
	"Document Printing",
	"Resume Creation",
	"Job Search support",
	"Grocery Shopping",
	"Fashion",
	"Social Media",
	"IT Support",
	"Graphic Design",
	"Delivery",
	"Ride sharing",
	"Catering/Cooking",
];

export const tasks = [
	{
		id: 1,
		college_id: 1,
		title: "Need help with my project",
		description:
			"I need help with my project, I am looking for someone who can help me with my project I need help with my project, I am looking for someone who can help me with my project I need help with my project, I am looking for someone who can help me with my pI need help with my project, I am looking for someone who can help me with my project I need help with my project, I am looking for someone who can help me with my project I need help with my project, I am looking for someone who can help me with my projectroject",
		category: "Academic Assistance",
		price: 1000,
		status: "open",
		created_at: "2024-02-13T17:04:40Z",
		expiry: "2024-02-14T22:34:39.698286Z",
		images: [
			"https://pbs.twimg.com/media/GHWFaH0W0AAmVx7?format=jpg&name=large",
			"https://via.placeholder.com/180",
			"https://via.placeholder.com/160",
		],
		files: [],
		name: "Sangarana Vinayaga Rangaraja Pandiyan",
		avatar: "https://via.placeholder.com/150",
		rating: 3.5,
	},
	{
		id: 2,
		college_id: 1,
		category: "Tutor Home/Virtual",
		title: "Maths exam preparation",
		description: "Maths exam coming up, need help with preparation",
		price: 500,
		status: "open",
		created_at: "2024-02-13T17:04:40Z",
		expiry: "2024-02-14T22:26:40.646631Z",
		// images: ["https://via.placeholder.com/150"],
		name: "Miabella",
		files: [],
		avatar: "https://via.placeholder.com/150",
		rating: 4.2,
	},
	{
		id: 3,
		college_id: 1,
		category: "Books Rent/Buy",
		title: "Need a book",
		description: "I need a book for my exams",
		price: 200,
		status: "open",
		created_at: "2024-02-13T17:04:40Z",
		expiry: "2024-02-14T22:26:40.646631Z",
		images: ["https://via.placeholder.com/150"],
		files: [],
		name: "John",
		avatar: "https://via.placeholder.com/150",
		rating: 4.8,
	},
	{
		id: 4,
		college_id: 1,
		category: "Vehicle Rent",
		title: "Need a bike",
		description: "I need a bike for rent",
		price: 200,
		status: "closed",
		created_at: "2024-02-13T17:04:40Z",
		expiry: "2024-02-14T22:26:40.646631Z",
		images: ["https://via.placeholder.com/150"],
		files: [],
		name: "Ethan Hunt",
		avatar: "https://via.placeholder.com/150",
		rating: 4.8,
	},
	{
		id: 5,
		college_id: 1,
		category: "Fashion",
		title: "Need to print documents",
		description: "I need to print some documents",
		price: 500,
		status: "open",
		created_at: "2024-02-13T17:04:40Z",
		expiry: "2024-02-14T22:26:40.646631Z",
		images: ["https://via.placeholder.com/150"],
		name: "Elon Musk",
		avatar: "https://via.placeholder.com/150",
		rating: 4.8,
	},
	{
		id: 6,
		college_id: 1,
		category: "Resume Creation",
		title: "Need to create a resume",
		description: "I need to create a resume",
		price: 200,
		status: "closed",
		created_at: "2024-02-13T17:04:40Z",
		expiry: "2024-02-14T22:26:40.646631Z",
		images: ["https://via.placeholder.com/150"],
		name: "Kosaksi Pasapugazh",
		avatar: "https://via.placeholder.com/150",
		rating: 4.8,
	},
	{
		id: 7,
		college_id: 1,
		category: "Job Search Support",
		title: "Need help with job search",
		description: "I need help with job search",
		price: 100,
		status: "open",
		created_at: "2024-02-13T17:04:40Z",
		expiry: "2024-02-14T22:26:40.646631Z",
		images: ["https://via.placeholder.com/150"],
		files: [],
		name: "Sara",
		avatar: "https://via.placeholder.com/150",
		rating: 4.8,
	},
];
